server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accountsdb
    username: adminAccount
    password: passwordAccount
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true